create table bank
(
    id bigint generated by default as identity
);

create table customer
(
    id bigint generated by default as identity,
    first_name varchar(200),
    last_name varchar(200),
    patronymic varchar(200),
    telephone_number varchar(200),
    email varchar(200),
    passport varchar(20)
);
insert into customer(last_name, first_name, patronymic, telephone_number, email, passport)
values ('Иванов', 'Иван', 'Иванович', '+7-999-999-99-99', 'ivanov@mail.ru', 1234123456);


